config/routes.rb
Rails.application.routes.draw do

  get 'calculators/addition'
  get 'calculators/subtraction'
  get 'calculators/multiplication'
  get 'calculators/division'
  get 'students/details' 
  get 'students/create'
  get 'students/show'
post  'students/show'
  get 'teachers/details'
  get 'teachers/create'
  get 'teachers/show'
post  'teachers/show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calculators_controller.rb
class CalculatorsController < ApplicationController
  def addition
  	@a=20
  	@b=30
  	puts "@a+@b"
  end
    def subtraction
    	@a=70
    	@b=20
    	puts "@a-@b"
  end
  def multiplication
  	@a=30
  	@b=40
  	puts "@a*@b"
  end
  def division
  	@a=70
  	@b=10
  	puts "@a/@b"
  end
end

app/controllers/facebook_controller.rb
class FacebookController < ApplicationController
  def create
  end

  def show
  	@fname = params[:fname]
  	@lname = params[:lname]
  	@fullname = params[:fullname]
  	@password = params[:password]
  end
end

app/controllers/mathamatics_controller.rb
class MathamaticsController < ApplicationController
  def calculator
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	def details
		@name="Bhupathi Naidu"
		@age=22
	end
	def create
	end
	def show
		@stu = Student.new(name: params[:name],age: params[:age],gender: params[:gender],address: params[:address])
		@stu.save
		@students=Student.all
	end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
	def details
		@name = "Sreenivas"
		@age = 40
		@address = "Anantapur"
	end
	def create
	end


	def show
	@t = Teacher.new(name: params[:name],age: params[:age],gender: params[:gender],address: params[:address])
  @t.save

@teachers=Teacher.all

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculators_helper.rb
module CalculatorsHelper
end

app/helpers/facebook_helper.rb
module FacebookHelper
end

app/helpers/mathamatics_helper.rb
module MathamaticsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/calculators/addition.html.erb
<center>
<h1> calculators addition</h1>

<p>@a=20</p>
<p>@b=30</p>
<p>addition is : <%=@a+@b%></p>
</center>

app/views/calculators/division.html.erb
<center>
<h1>Calculators  division</h1>
<p>@a=70</p>
<p>@b=10</p>
<p>division is : <%=@a/@b%></p>
</center>

app/views/calculators/multiplication.html.erb
<center>
<h1>Calculators multiplication</h1>
<p>@a=30</p>
<p>@b=40</p>
<p>multiplication is : <%=@a*@b%></p>
</center>

app/views/calculators/subtraction.html.erb
<center>
<h1>Calculators  subtraction</h1>
<p>	@a=70</p>
<p> @b=20</p>
<p>subtration is : <%=@a-@b%></p>
</center>

app/views/facebook/create.html.erb
<%= form_tag facebook_show_path do %>
<%= field_set_tag do %>
<legend> facebook signin page</legend>
<p>
	<%= label_tag 'fname' %>
	<%= text_field_tag 'fname' %>
</p>
<p>
	<%= label_tag 'lname' %>
	<%= text_field_tag 'lname' %>
</p>
<p>
	<%= label_tag 'fullname' %>
	<%= text_field_tag 'fullname' %>
</p>
<p>
	<%= label_tag 'password' %>
	<%= text_field_tag 'password' %>
</p>
<p>
	<%= label_tag 'confirmpassword' %>
	<%= text_field_tag 'confirmpassword' %>
</p>
<p>
	<%= submit_tag "submit" %>
</p>   
<p>
    <%= label_tag 'Remember me' %>
    <%= check_box_tag 'Remember me' %>
</p>
<% end %>
<% end %>

app/views/facebook/show.html.erb
<h1>Facebook sign page</h1>
<p>fname : <%= @fname %> </p>
<p>lname : <%= @lname %> </p>
<p>fullname : <%= @fullname %> </p>
<p>password : <%= @password %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <h1 align="center"> ***** Calculators project*****</h1>
  <div class="sidebar">
  <h3>  <%=link_to "Addition", calculators_addition_path=%><br/></h3>
  <h3> <%=link_to "Subtraction", calculators_subtraction_path=%><br/></h3>
  <h3> <%=link_to "Multiplication", calculators_multiplication_path=%><br/></h3>
   <h3> <%=link_to "Division", calculators_division_path=%><br/></h3>
  </div>
  <div class="sidebar" align="right">
  <h3>  <%=link_to "students details", students_details_path=%><br/></h3>
  <h3>  <%=link_to "teachers details", teachers_details_path=%><br/></h3>
</div>
    <title>School</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background: #4ef442;">
    <%= yield %>
  </body>
 
    <br /><br /><br /><br /><br /><br /><br /> <br />  
     <h1 align="center"> ******End of project*****</h1>
</html>

app/views/layouts/facebook.html.erb
<!DOCTYPE html>
<html>
<head>
  <h1 align="center"> facebook sign in page</h1>
 
    <title>School</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background: blue">
    <%= yield %>
  </body>
</html>

app/views/layouts/mathamatics.html.erb
<!DOCTYPE html>
<html>
<head>
  <h1 align="center"> ***** Calculators project*****</h1>
 
    <title>School</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background: lightgreen">
    <%= yield %>
  </body>
 
    <br /><br /><br /><br /><br /><br /><br /> <br />  
     <h1 align="center"> ******End of project*****</h1>
</html>

app/views/layouts/students.html.erb
<!DOCTYPE html>
<html>
<head>
<h1 align="center" ><font color="blue">****** HEADER *****</font></h1>
  <h1> Student Details</h1>
 
    <title>School</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background: lightyellow">
    <%= yield %>
  </body>
   <h1 align="center">****** FOOTER ***** </h1>
</html>

app/views/layouts/teachers.html.erb
<!DOCTYPE html>
<html>
<head>
  <h1 align="center"> teachers details</h1>
 
    <title>School</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background: lightblue">
    <%= yield %>
  </body>
</html>

app/views/mathamatics/calculator.html.erb
<%= form_tag mathamatics_calculator_path do%>
<table border="2px" width="300px" cellspacing="20px" cellpadding="10px" align="center">
	<tr>
		<td colspan="3" style="border: 0px">
	<%=text_field_tag 'txtAns'%>
</td>
<td style="background-color: blue;">clear</td>
<td style="background-color: red;">AC</td>
<tr>
	<td>7</td>
	<td>8</td>
	<td>9</td>
	<td>*</td>
	<td>=</td>
</tr>
<tr>
	<td>4</td>
	<td>5</td>
	<td>6</td>
	<td>-</td>
	<td>%</td>
</tr>
<tr>
	<td>1</td>
	<td>2</td>
	<td>3</td>
	<td rowspan="2">+</td>
	<td>&</td>
</tr>
<tr>
	<td>log</td>
	<td>0</td>
	<td>.</td>
	<td>/ </td>
</tr>
</table>
<% end %>

app/views/students/create.html.erb
<%= form_tag students_show_path do %>
<p>
	<%= label_tag "name" %>
	<%= text_field_tag :name %>
</p>
<p>
	<%= label_tag "age" %>
	<%= text_field_tag :age %>
</p>
<p>
	<%= label_tag 'male' %> <%= radio_button_tag 'gender', 'male' %>
	<%= label_tag 'female' %> <%= radio_button_tag 'gender', 'male' %>
</p>
<p>
	<%= label_tag 'address' %>
	<%= text_area_tag :address %>
	
</p>
<p>
	<%= submit_tag "submit" %>
</p> 
<% end %>

app/views/students/details.html.erb
<center>
<h1> STUDENT DETAILS</h1>
<P> Name : <%= @name %> </P>
<P> Age : <%= @age %> </P>
</center>

app/views/students/show.html.erb
<table border="2">
<thead>
	<th> name </th>
	<th> age </th>
	<th> gender </th>
	<th> address </th>
<tbody>
<% @students.each do |s| %>
 <% if s.name == nil %>
 	<% puts "kishore" %>
 	<% next %>
 <% end %>
 <tr>
 	<td> <%= s.name %> </td>
	<td> <%= s.age %> </td>
	<td> <%= s.gender %> </td>
	<td> <%= s.address %></td>
 </tr>
<% end %>
</tbody>
</thead>
</table>

app/views/teachers/create.html.erb
<%= form_tag teachers_show_path do %>
	<%= label_tag "name" %>
	<%= text_field_tag :name %>
</p>
	<%= label_tag "age" %>
	<%= number_field_tag :age %>
</p>
<p>
	<%= label_tag 'male' %> <%= radio_button_tag 'gender', 'male' %>
	<%= label_tag 'female' %> <%= radio_button_tag 'gender', 'male' %>
</p>
<p>
	<%= label_tag 'address' %>
	<%= text_area_tag :address %>
</p>
<p>
	<%= submit_tag "submit" %>
</p> 
<% end %>

app/views/teachers/details.html.erb
<center>
<h1> TEACHERS DETAILS</h1>
<P> Name : <%= @name %> </P>
<P> Age : <%= @age %> </P>
<P> Address : <%= @address%> </P>
</center>

app/views/teachers/show.html.erb
<h1> Teachers details </h1>
<%= @teachers.each do |t| %>
<p>
	Name : <%= t.name %>
	Age : <%= t.age %>
	Gender : <%= t.gender %>
	Address : <%= t.address %>
</p>
<% end %>